### ISSUE TITLE
Unbalanced tree can be used to forge a replica balanced tree

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/merkle-lib#1]
See https://github.com/bitcoinjs/merkle-lib/commit/dc3975f020a2b025efb77aea79557f3bd0adef7b for test fixture,  and https://bitcointalk.org/?topic=102395 for description.

@fanatid naturally `bitcoinjs-lib` is vulnerable to this due to its lacking consensus model... what are your thoughts?

Also,  I like using this library outside of `bitcoin` applications,  so it'd be nice to not have to worry about such a basic flaw.
The issue is this line: https://github.com/bitcoinjs/merkle-lib/blob/master/index.js#L8

Thoughts on a fix?

**Comment by dcousens** [comment]
**tl;dr** `left` has been allowed to be ambiguous with `right` in an unbalanced tree,  therefore leading to obvious implication that an artificially created tree can be created where `left` is duplicated,  leading to the same root hash.

Any approach we'd make would need to

**Comment by fanatid** [comment]
Not sure that we can do something here, this bugs comes from design :(

**Comment by dcousens** [comment]
@fanatid thoughts on what we should put in the README then?

**Comment by fanatid** [comment]
>@fanatid thoughts on what we should put in the README then?

Yes, definitely.

**Comment by dcousens** [comment]
Added a README warning. https://github.com/bitcoinjs/merkle-lib/commit/2cb00a5c9f13b368d50b1040dacc87450fb08919
